# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hoonmin Kim
tagline:          'Memcached, Cache, Hadoop, Blogging, Home-Network'
url:              http://hoonmin.github.io
shorturl:         hoonmin.github.io

author:
  name:           'Hoonmin Kim'
  url:            https://facebook.com/harebox

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/hoonmin/hoonmin.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
